version: '3.8'
services:
  odoo:
    image: odoo:10.0
    container_name: odoo10
    depends_on:
      - db
    ports:
      - '8787:8787'
      - '8072:8072'
    volumes:
      - odoo13-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    #      - 443:443
    volumes:
      - ./nginx/config/conf.d:/etc/nginx/conf.d
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
  #      - ./certbot/conf:/etc/nginx/ssl
  #      - ./certbot/data:/var/www/html
  #  certbot:
  #    container_name: certbot
  #    image: certbot/certbot:latest
  #  command: -i Odoo-Docker-Optimized-master -d odoo10-network --test-enable
  #    volumes:
  #      - ./certbot/conf:/etc/letsencrypt
  #      - ./certbot/logs:/var/log/letsencrypt
  #      - ./certbot/data:/var/www/html
  db:
    image: postgres:10
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - odoo13-db-data:/var/lib/postgresql/data/pgdata
#  haproxy:
#    image: haproxy:latest
#    container_name: haproxy
#    ports:
#      - "80:80"
#    volumes:
#      - ./haproxy:/usr/local/etc/haproxy:ro
volumes:
  odoo13-web-data:
  odoo13-db-data:
networks:
  default:
    external:
      name: odoo10-network
